### ISSUE TITLE
User Story: Create User Account

### ISSUE THREAD

**Issue by AmirShkolnik** [AmirShkolnik/DivingCenter#7]
#### Description
- **As a** user **I can** create an account **so that** I can access personalized features of the diving center website.

---

#### Acceptance Criteria

1. User can access a registration page
2. User can input necessary information (e.g., name, email, password)
3. User can log in with newly created credentials

---

#### Tasks

- [x] `Design and implement registration form`
- [x] `Create database schema for user accounts`
- [x] `Implement user authentication system`

**Belonging to**: #1 EPIC 1: User Authentication and Profile Management
